### PR TITLE
Setup Ansible inventory for PSDR

### PR DESCRIPTION
**Pull request by bkus**
I have master setup to require 2 reviewer signoffs.

### CODE REVIEW

**Review by osburn — APPROVED** [review]

**Comment by turnrye** [comment]
Im not a reviewer here, but this change makes sense to me.

**Comment by bkus** [comment]
> Im not a reviewer here, but this change makes sense to me.

Sorry, didn't mean to spam you.  It's only gonna get worse.  Choose wisely!  :)

**Comment by nigelvh** [comment]
LGTM. 👍

**Review by nigelvh — APPROVED** [review]

**Review by kd7lxl — APPROVED** [review]
Please be ready to assist other netops using commands shared in previous email threads, since their `-i` args will now point to the wrong path.

**Pull request merged**
